### ISSUE TITLE
Would you consider turning over this name?

### ISSUE THREAD

**Issue by frankwiles** [frankwiles/django-tracer#1]
Hi, 

I have a project I've been working on for tracing incoming requests to Django, mostly for use with DRF APIs that then talk to other internal services and noticed you had this name, but don't appear to be actively using it.  

If you'd consider turning it over to me that would be awesome, but completely understand if you don't want to! Thanks for taking the time to consider it.

**Comment by rhblind** [comment]
Hey, absolutely! I'll transfer the repo to you so you can do whatever you want with it! This name was for a project I never got time to do 😋

**Comment by frankwiles** [comment]
That's awesome @rhblind can we also work out a transfer for PyPI? I'd like to be able to release this little utility.  Thanks!

**Comment by rhblind** [comment]
No problem, yes of course! What's your username on pypi?

**Comment by frankwiles** [comment]
Awesome, username on pypi is 'fwiles' thanks!

**Comment by frankwiles** [comment]
Hi @rhblind any luck in transferring the pypi registration yet?

**Comment by rhblind** [comment]
Hi sorry, totally forgot about it. Been on vacation. I'll fix it now!

**Comment by rhblind** [comment]
Have added you as owner on the pypi registration, but I cannot remove myself. Can you see if you're able to do it? If not, I'll have to delete the whole repo from pypi in order to free up the name.

**Comment by frankwiles** [comment]
Awesome yep I was able to remove you.  Thanks so much!

**Comment by rhblind** [comment]
Great, no problem!
